/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PolyPro.frame;

import com.PolyPro.DAO.ChuyenDeDAO;
import com.PolyPro.entity.ChuyenDe;
import com.PolyPro.helper.DesignHelper;
import com.PolyPro.helper.DialogHelper;
import com.PolyPro.helper.ShareHelper;
import com.PolyPro.helper.ValidateHelper;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenTruongChinh
 */
public class ChuyenDeJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ChuyenDeJFrame
     */
    public ChuyenDeJFrame() {
        initComponents();
        setTitleTable();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lbl_image = new javax.swing.JLabel();
        txt_idCD = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_time = new javax.swing.JTextField();
        txt_tuition = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_content = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_prev = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_list = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ CHUYÊN ĐỀ");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        lbl_image.setToolTipText("null");
        lbl_image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbl_image.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_imageMouseClicked(evt);
            }
        });

        txt_idCD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_idCDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_idCDFocusLost(evt);
            }
        });

        txt_name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nameFocusLost(evt);
            }
        });

        txt_time.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_timeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_timeFocusLost(evt);
            }
        });

        txt_tuition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_tuitionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tuitionFocusLost(evt);
            }
        });

        txt_content.setColumns(20);
        txt_content.setRows(5);
        txt_content.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_contentFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_contentFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txt_content);

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btn_add.setBackground(new java.awt.Color(0, 204, 0));
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/PolyPro/icons/Add.png"))); // NOI18N
        btn_add.setText("THÊM");
        btn_add.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btn_add.setPreferredSize(new java.awt.Dimension(100, 40));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 51, 0));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/PolyPro/icons/Delete.png"))); // NOI18N
        btn_delete.setText("XÓA");
        btn_delete.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_new.setBackground(new java.awt.Color(0, 204, 204));
        btn_new.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/PolyPro/icons/refresh-icon.png"))); // NOI18N
        btn_new.setText("MỚI");
        btn_new.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_last.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_last.setText(">|");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        btn_next.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_next.setText(">>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_prev.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_prev.setText("<<");
        btn_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevActionPerformed(evt);
            }
        });

        btn_first.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_first.setText("|<");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 255, 0));
        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/PolyPro/icons/Edit.png"))); // NOI18N
        btn_edit.setText("SỬA");
        btn_edit.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btn_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_editMouseClicked(evt);
            }
        });
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_idCD, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_name)
                                    .addComponent(txt_tuition, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                        .addComponent(btn_first)
                        .addGap(18, 18, 18)
                        .addComponent(btn_prev)
                        .addGap(18, 18, 18)
                        .addComponent(btn_next)
                        .addGap(18, 18, 18)
                        .addComponent(btn_last)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_idCD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_time, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tuition, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_first)
                        .addComponent(btn_prev)
                        .addComponent(btn_next)
                        .addComponent(btn_last)
                        .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        tabs.addTab("CẬP NHẬT", jPanel1);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        tbl_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_list);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))
        );

        tabs.addTab("DANH SÁCH", jPanel2);

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tabs)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idCDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idCDFocusGained
        // TODO add your handling code here:
        if (txt_idCD.getText().equals(" Mã chuyên đề")) {
            txt_idCD.setText("");
            txt_idCD.requestFocus();
            DesignHelper.deleteTextField(txt_idCD);
        }
    }//GEN-LAST:event_txt_idCDFocusGained

    private void txt_idCDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idCDFocusLost
        // TODO add your handling code here:
        if (txt_idCD.getText().length() == 0) {
            DesignHelper.addTextField(txt_idCD);
            txt_idCD.setText(" Mã chuyên đề");
            txt_idCD.setSize(250, 35);
        }
    }//GEN-LAST:event_txt_idCDFocusLost

    private void txt_nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusGained
        // TODO add your handling code here:
        if (txt_name.getText().equals(" TÃªn chuyÃªn Ä‘á»�")) {
            txt_name.setText("");
            txt_name.requestFocus();
            DesignHelper.deleteTextField(txt_name);
        }
    }//GEN-LAST:event_txt_nameFocusGained

    private void txt_nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nameFocusLost
        // TODO add your handling code here:
        if (txt_name.getText().length() == 0) {
            txt_name.setText(" Tên Chuyên đề");
            DesignHelper.addTextField(txt_name);
            txt_name.setSize(250, 35);
        }
    }//GEN-LAST:event_txt_nameFocusLost

    private void txt_timeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_timeFocusGained
        // TODO add your handling code here:
        if (txt_time.getText().equals(" Thời lượng (Giờ)")) {
            txt_time.setText("");
            txt_time.requestFocus();
            DesignHelper.deleteTextField(txt_time);
        }
    }//GEN-LAST:event_txt_timeFocusGained

    private void txt_timeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_timeFocusLost
        // TODO add your handling code here:
        if (txt_time.getText().length() == 0) {
            txt_time.setText(" Thời lượng (Giờ)");
            DesignHelper.addTextField(txt_time);
            txt_time.setSize(250, 35);
        }
    }//GEN-LAST:event_txt_timeFocusLost

    private void txt_tuitionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tuitionFocusGained
        // TODO add your handling code here:
        if (txt_tuition.getText().equals(" Học phí")) {
            txt_tuition.setText("");
            txt_tuition.requestFocus();
            DesignHelper.deleteTextField(txt_tuition);
        }
    }//GEN-LAST:event_txt_tuitionFocusGained

    private void txt_tuitionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tuitionFocusLost
        // TODO add your handling code here:
        if (txt_tuition.getText().length() == 0) {
            txt_tuition.setText(" Học phí");
            DesignHelper.addTextField(txt_tuition);
            txt_tuition.setSize(250, 35);
        }
    }//GEN-LAST:event_txt_tuitionFocusLost

    private void txt_contentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contentFocusGained
        // TODO add your handling code here:
        if (txt_content.getText().equals(" Mô tả chuyên đề")) {
            txt_content.setText("");
            txt_content.requestFocus();
            DesignHelper.deleteTextArea(txt_content);
        }
    }//GEN-LAST:event_txt_contentFocusGained

    private void txt_contentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_contentFocusLost
        // TODO add your handling code here:
        if (txt_content.getText().length() == 0) {
            txt_content.setText(" Mô tả chuyên đề");
            DesignHelper.addTextArea(txt_content);
        }
    }//GEN-LAST:event_txt_contentFocusLost

    private void lbl_imageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_imageMouseClicked
        // TODO add your handling code here:
        this.chooseImage();
    }//GEN-LAST:event_lbl_imageMouseClicked

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if (isValidate()) {
            this.insert();
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btn_prevActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btn_lastActionPerformed

    private void tbl_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tbl_list.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tbl_listMouseClicked

    private void btn_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editMouseClicked
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btn_editMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenDeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenDeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenDeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenDeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChuyenDeJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_prev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_list;
    private javax.swing.JTextArea txt_content;
    private javax.swing.JTextField txt_idCD;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_time;
    private javax.swing.JTextField txt_tuition;
    // End of variables declaration//GEN-END:variables

    public void init() {
        setLocationRelativeTo(null);
        fillToTable();
        this.row = -1;
        this.updateStatus();
        setText();
        loadImage("icons\\avt_default.jpg");
    }

    public ImageIcon loadImage(String image) {
        ImageIcon imageI = new ImageIcon(image);
        Image img = imageI.getImage();
        ImageIcon icon = new ImageIcon(img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), img.SCALE_SMOOTH));
        lbl_image.setIcon(icon);
        return icon;
    }

    DefaultTableModel model;

    public void setTitleTable() {
        model = new DefaultTableModel();
        model.addColumn("MÃ CD");
        model.addColumn("TÊN CD");
        model.addColumn("THỜI LƯỢNG");
        model.addColumn("HỌC PHÍ");
        model.addColumn("HÌNH");
        tbl_list.setModel(model);

        DesignHelper.setTable(tbl_list);
    }

    public void setText() {
        ChuyenDe cd = new ChuyenDe();
        txt_idCD.setText(" Mã chuyên đề");
        txt_name.setText(" Tên chuyên đề");
        txt_time.setText(" Thời lượng (Giờ)");
        txt_tuition.setText(" Học phí");
        txt_content.setText(" Mô tả chuyên đề");
        DesignHelper.addTextField(txt_idCD);
        DesignHelper.addTextField(txt_name);
        DesignHelper.addTextField(txt_time);
        DesignHelper.addTextField(txt_tuition);
        DesignHelper.addTextArea(txt_content);
        txt_idCD.setSize(250, 35);
        txt_name.setSize(250, 35);
        txt_tuition.setSize(250, 35);
        txt_time.setSize(250, 35);
        loadImage("icons\\avt_default.jpg");
    }

    public void deletePlaceHolder() {
        DesignHelper.deleteTextField(txt_idCD);
        DesignHelper.deleteTextField(txt_name);
        DesignHelper.deleteTextField(txt_time);
        DesignHelper.deleteTextField(txt_tuition);
        DesignHelper.deleteTextArea(txt_content);
    }

    /* viáº¿t mÃ£ cho cÃ¡c chá»©c nÄƒng*/
    // Khai bÃ¡o
    ChuyenDeDAO dao = new ChuyenDeDAO(); // lÃ m viá»‡c vá»›i báº£ng CHUYENDE
    int row = -1; // HÃ ng Ä‘Æ°á»£c chá»�n trÃªn table 
    JFileChooser fileChooser = new JFileChooser();

    void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_list.getModel(); // láº¥y model table ra (nÆ¡i chá»©a dá»¯ liá»‡u Ä‘á»ƒ hiá»‡n lÃªn table)
        model.setRowCount(0); // xÃ³a all hÃ ng trÃªn table
        try {
            List<ChuyenDe> list = dao.selectAll(); // Ä�á»�c dá»¯ liá»‡u tá»« database
            for (ChuyenDe cd : list) {
                model.addRow(new Object[]{
                    cd.getMaCD(),
                    cd.getTenCD(),
                    cd.getThoiLuong(),
                    cd.getHocPhi(),
                    cd.getHinh(),
                    cd.getMoTa()}); // thÃªm 1 hÃ ng vÃ o table
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void chooseImage() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            ShareHelper.saveLogo(file); // lÆ°u vÃ o thÆ° má»¥c logos
            ImageIcon icon = ShareHelper.readLogo(file.getName()); // Ä‘á»�c hÃ¬nh tá»« logos
            lbl_image.setIcon(icon);
            lbl_image.setToolTipText(file.getName()); // giá»¯ tÃªn hÃ¬nh trong tooltip
        }
    }

    void setBackgroundDefault() {
        DesignHelper.setBackgroundDefault(txt_idCD);
        DesignHelper.setBackgroundDefault(txt_name);
        DesignHelper.setBackgroundDefault(txt_time);
        DesignHelper.setBackgroundDefault(txt_tuition);
        DesignHelper.setBackgroundDefault(txt_content);
    }

    void setBackgroundTrue() {
        DesignHelper.setBackgroundTrue(txt_idCD);
        DesignHelper.setBackgroundTrue(txt_name);
        DesignHelper.setBackgroundTrue(txt_time);
        DesignHelper.setBackgroundTrue(txt_tuition);
        DesignHelper.setBackgroundTrue(txt_content);
    }

    public void clear() {
        ChuyenDe cd = new ChuyenDe();
        setText();
        lbl_image.setToolTipText("null");
        setBackgroundDefault();
        this.row = -1;
        this.updateStatus();
    }

    public void insert() {
        ChuyenDe cd = getForm();
        try {
            dao.insert(cd);
            this.fillToTable();
            setText();
            this.clear();
            DialogHelper.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Thêm mới thất bại!" + e);
        }
    }

    public void update() {
        ChuyenDe cd = getForm();
        try {
            dao.update(cd);
            this.fillToTable();
            DialogHelper.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại!");
        }
    }

    public void delete() {
        String maCD = txt_idCD.getText();
        if (DialogHelper.confirm(this, "Bạn có muốn xóa hay không?")) {
            try {
                dao.delete(maCD);
                this.fillToTable();
                clear();
                setText();
                DialogHelper.alert(this, "Xóa thành công!");
            } catch (Exception e) {
                DialogHelper.alert(this, "Xóa thất bại!");
            }
        }
    }

    public void setForm(ChuyenDe cd) {
        setBackgroundDefault();
        txt_idCD.setText(cd.getMaCD());
        txt_name.setText(cd.getTenCD());
        txt_tuition.setText(String.valueOf(cd.getHocPhi()));
        txt_time.setText(String.valueOf(String.valueOf(cd.getThoiLuong())));
        lbl_image.setToolTipText(cd.getHinh());
        if (cd.getHinh() != null) {
            lbl_image.setToolTipText(cd.getHinh());
            lbl_image.setIcon(ShareHelper.readLogo(cd.getHinh()));
        }
        txt_content.setText(cd.getMoTa());
    }

    public ChuyenDe getForm() {
        ChuyenDe cd = new ChuyenDe();
        cd.setMaCD(txt_idCD.getText());
        cd.setTenCD(txt_name.getText());
        cd.setHocPhi(Double.parseDouble(txt_tuition.getText()));
        cd.setThoiLuong(Integer.parseInt(txt_time.getText()));
        cd.setHinh(lbl_image.getToolTipText());
        cd.setMoTa(txt_content.getText());
        return cd;
    }

    public void edit() {
        String maCD = (String) tbl_list.getValueAt(this.row, 0);
        ChuyenDe cd = dao.selectById(maCD);
        this.setForm(cd);
        if(cd.getHinh().equalsIgnoreCase("null")){
            loadImage("icons\\avt_default.jpg");
        }
        deletePlaceHolder();
        tabs.setSelectedIndex(0);
        this.updateStatus();
    }

    public void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tbl_list.getRowCount() - 1);

        // Tráº¡ng thÃ¡i form
        txt_idCD.setEditable(!edit);
        btn_add.setEnabled(!edit);
        btn_edit.setEnabled(edit);
        btn_delete.setEnabled(edit);

        // Tráº¡ng thÃ¡i Ä‘iá»�u hÆ°á»›ng
        btn_first.setEnabled(edit && !first);
        btn_prev.setEnabled(edit && !first);
        btn_next.setEnabled(edit && !last);
        btn_last.setEnabled(edit && !last);
    }

    public void first() {
        this.row = 0;
        this.edit();
    }

    public void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    public void next() {
        if (this.row < tbl_list.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    public void last() {
        this.row = tbl_list.getRowCount() - 1;
        this.edit();
    }

    boolean isValidate() {
        String notification = "";
        ChuyenDe cd = dao.selectById(txt_idCD.getText());
        if (txt_idCD.getText().equalsIgnoreCase(" Mã chuyên đề")) {
            notification += "Vui lòng nhập mã chuyên đề\n";
            DesignHelper.setBackgroundFalse(txt_idCD);
        } else if (ValidateHelper.checkMaCD(txt_idCD) == false) {
            notification += "Mã chuyên đề phải từ 5 ký tự \n Không sử dụng ký tự đặc biệt!\n";
        } else if (cd != null) {
            notification += "Mã chuyên đề đã tồn tại\n";
            DesignHelper.setBackgroundFalse(txt_idCD);
        }

        if (txt_name.getText().equalsIgnoreCase(" Tên chuyên đề")) {
            notification += "Vui lòng nhập tên chuyên đề!\n";
            DesignHelper.setBackgroundFalse(txt_name);
        } else if (ValidateHelper.checkNameForm(txt_name) == false) {
            notification += "Tên chuyên đề phải từ 3 - 50 ký tự\n";
        }

        if (txt_time.getText().equalsIgnoreCase(" Thời lượng (Giờ)")) {
            notification += "Vui lòng nhập thời lượng\n";
            DesignHelper.setBackgroundFalse(txt_time);
        } else if (ValidateHelper.checkTime(txt_time) == false) {
            notification += "Thời lượng phải lớn hơn hoặc bằng 0!\n";
        }

        if (txt_tuition.getText().equalsIgnoreCase(" Học phí")) {
            notification += "Vui lòng nhập học phí\n";
            DesignHelper.setBackgroundFalse(txt_tuition);
        } else if (ValidateHelper.checkHocPhi(txt_tuition) == false) {
            notification += "Học phí phải lớn hơn hoặc bằng 0!\n";
        }

        if (txt_content.getText().equalsIgnoreCase(" Mô tả chuyên đề")) {
            notification += "Vui lòng nhập mô tả!\n";
            DesignHelper.setBackgroundFalse(txt_content);
        } else if (ValidateHelper.checkNote(txt_content) == false) {
            notification += "Mô tả phải từ 3-255 ký tự!\n";
        }

        if (notification != "") {
            DialogHelper.alert(this, notification);
            return false;
        } else {
            setBackgroundTrue();
            return true;
        }
    }

}
