/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PolyPro.frame;

import com.PolyPro.DAO.NhanVienDAO;
import com.PolyPro.entity.NhanVien;
import com.PolyPro.helper.DialogHelper;
import com.PolyPro.helper.ShareHelper;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;
/**
 *
 * @author NguyenTruongChinh
 */
public class DangNhapJDialog extends javax.swing.JDialog {

    /**
     * Creates new form DangNhapJDialog
     */
    public DangNhapJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        lbl_logo = new javax.swing.JLabel();
        kGradientPanel2 = new com.k33ptoo.components.KGradientPanel();
        txt_maNV = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        btn_login = new com.k33ptoo.components.KButton();
        btn_stop = new com.k33ptoo.components.KButton();
        lbl_title = new javax.swing.JLabel();
        lbl_forgotPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        kGradientPanel1.setkBorderRadius(0);
        kGradientPanel1.setkEndColor(new java.awt.Color(255, 255, 153));
        kGradientPanel1.setkGradientFocus(200);
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 255, 255));
        kGradientPanel1.setLayout(new java.awt.BorderLayout());

        lbl_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/PolyPro/icons/Security-User-Shield-icon.png"))); // NOI18N
        kGradientPanel1.add(lbl_logo, java.awt.BorderLayout.CENTER);

        getContentPane().add(kGradientPanel1, java.awt.BorderLayout.LINE_START);

        kGradientPanel2.setkBorderRadius(0);
        kGradientPanel2.setkEndColor(new java.awt.Color(255, 255, 153));
        kGradientPanel2.setkGradientFocus(50);
        kGradientPanel2.setkStartColor(new java.awt.Color(102, 255, 255));

        txt_maNV.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        txt_maNV.setForeground(new java.awt.Color(102, 102, 102));
        txt_maNV.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_maNVFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_maNVFocusLost(evt);
            }
        });

        txt_password.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        txt_password.setForeground(new java.awt.Color(102, 102, 102));
        txt_password.setEchoChar('\u0000');
        txt_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passwordFocusLost(evt);
            }
        });

        btn_login.setText("Đăng nhập");
        btn_login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_login.setkHoverEndColor(new java.awt.Color(0, 255, 255));
        btn_login.setkHoverForeGround(new java.awt.Color(0, 0, 204));
        btn_login.setkHoverStartColor(new java.awt.Color(255, 255, 0));
        btn_login.setkSelectedColor(new java.awt.Color(0, 0, 204));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        btn_stop.setText("Kết thúc");
        btn_stop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_stop.setkHoverEndColor(new java.awt.Color(0, 255, 255));
        btn_stop.setkHoverForeGround(new java.awt.Color(0, 0, 204));
        btn_stop.setkHoverStartColor(new java.awt.Color(255, 255, 0));
        btn_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stopActionPerformed(evt);
            }
        });

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 0, 0));
        lbl_title.setText("ĐĂNG NHẬP");

        lbl_forgotPassword.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lbl_forgotPassword.setForeground(new java.awt.Color(0, 0, 204));
        lbl_forgotPassword.setText("Quên mật khẩu?");
        lbl_forgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_forgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_forgotPasswordMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_forgotPasswordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_forgotPasswordMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_title)
                            .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(kGradientPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_forgotPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_stop, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_title)
                .addGap(32, 32, 32)
                .addComponent(txt_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_forgotPassword)
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_stop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(kGradientPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        login();
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopActionPerformed
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_btn_stopActionPerformed

    private void txt_maNVFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_maNVFocusGained
        // TODO add your handling code here:
        if(txt_maNV.getText().equals(" Mã nhân viên")){
            txt_maNV.setText("");
            txt_maNV.requestFocus();
            deletePlaceHolder(txt_maNV);
        }
    }//GEN-LAST:event_txt_maNVFocusGained

    private void txt_maNVFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_maNVFocusLost
        // TODO add your handling code here:
        if(txt_maNV.getText().length() == 0){
            txt_maNV.setText(" Mã nhân viên");
            addPlaceHolder(txt_maNV);
        }
    }//GEN-LAST:event_txt_maNVFocusLost

    private void txt_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusGained
        // TODO add your handling code here:
        if(txt_password.getText().equals(" Mật khẩu")){
            txt_password.setText("");
            txt_password.requestFocus();
            txt_password.setEchoChar('\u25cf');
            deletePlaceHolder(txt_password);
        }
    }//GEN-LAST:event_txt_passwordFocusGained

    private void txt_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passwordFocusLost
        // TODO add your handling code here:
        if(txt_password.getText().length() == 0){
            txt_password.setText(" Mật khẩu");
            txt_password.setEchoChar('\u0000');
            addPlaceHolder(txt_password);
        }
    }//GEN-LAST:event_txt_passwordFocusLost

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formWindowGainedFocus

    private void lbl_forgotPasswordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotPasswordMouseEntered
        // TODO add your handling code here:
        lbl_forgotPassword.setForeground(new Color(0,204,51));
    }//GEN-LAST:event_lbl_forgotPasswordMouseEntered

    private void lbl_forgotPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotPasswordMouseExited
        // TODO add your handling code here:
        lbl_forgotPassword.setForeground(new Color(0,0,204));
    }//GEN-LAST:event_lbl_forgotPasswordMouseExited

    private void lbl_forgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_forgotPasswordMouseClicked
        // TODO add your handling code here:
        openForgotPass();
    }//GEN-LAST:event_lbl_forgotPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhapJDialog dialog = new DangNhapJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    void init(){
        setLocationRelativeTo(null);
        setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        setText();
    }
    
    void setText(){
        txt_maNV.setText(" Mã nhân viên");
        txt_password.setText(" Mật khẩu");
        addPlaceHolder(txt_maNV);
        addPlaceHolder(txt_password);
    }
    
    void addPlaceHolder(JTextField jtf){
        Font font = jtf.getFont();
        font = font.deriveFont(Font.ITALIC);
        jtf.setFont(font);
        jtf.setForeground(Color.GRAY);
    }
    
    void deletePlaceHolder(JTextField jtf){
        Font font = jtf.getFont();
        font = font.deriveFont(Font.PLAIN);
        jtf.setFont(font);
        jtf.setForeground(Color.BLACK);
    }
    
    public void openForgotPass(){
        this.dispose();
        new QuenMatKhauJFrame().setVisible(true);
    }
    
    NhanVienDAO dao = new NhanVienDAO();
    
    void login(){
        String maNV = txt_maNV.getText();
        String matKhau = new String(txt_password.getPassword());
        
        NhanVien nv = dao.selectById(maNV);
        if(nv == null){
            DialogHelper.alert(this, "Sai tên đăng nhập");
        }
        else if(!matKhau.equals(nv.getMatKhau())){
            DialogHelper.alert(this, "Sai mật khẩu");
        }
        else{
            ShareHelper.user = nv;
            this.dispose();
        }
        
    }
    
    void exit(){
        if(DialogHelper.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")){
            System.exit(0);
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton btn_login;
    private com.k33ptoo.components.KButton btn_stop;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel2;
    private javax.swing.JLabel lbl_forgotPassword;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_maNV;
    private javax.swing.JPasswordField txt_password;
    // End of variables declaration//GEN-END:variables
}
