/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PolyPro.frame;

import com.PolyPro.DAO.ChuyenDeDAO;
import com.PolyPro.DAO.KhoaHocDAO;
import com.PolyPro.DAO.NguoiHocDAO;
import com.PolyPro.entity.ChuyenDe;
import com.PolyPro.entity.KhoaHoc;
import com.PolyPro.entity.NguoiHoc;
import com.PolyPro.helper.DateHelper;
import com.PolyPro.helper.DialogHelper;
import com.PolyPro.helper.DesignHelper;
import com.PolyPro.helper.ShareHelper;
import com.PolyPro.helper.ValidateHelper;
import java.awt.Color;
import java.awt.Font;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenTruongChinh
 */
public class KhoaHocJFrame extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form KhoaHocJFrame
     */
    public KhoaHocJFrame() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_openningDay = new javax.swing.JTextField();
        txt_tuition = new javax.swing.JTextField();
        txt_time = new javax.swing.JTextField();
        txt_dateCreated = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_note = new javax.swing.JTextArea();
        btn_add = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_delete = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        btn_last = new javax.swing.JButton();
        btn_next = new javax.swing.JButton();
        btn_prev = new javax.swing.JButton();
        btn_first = new javax.swing.JButton();
        txt_creator = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        lbl_tenCD = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_list = new javax.swing.JTable();
        cbo_thematic = new javax.swing.JComboBox<>();
        lbl_viewAll = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 204, 51));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("QUẢN LÝ KHÓA HỌC");

        tabs.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        txt_openningDay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_openningDayFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_openningDayFocusLost(evt);
            }
        });

        txt_tuition.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_tuitionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tuitionFocusLost(evt);
            }
        });

        txt_time.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_timeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_timeFocusLost(evt);
            }
        });

        txt_dateCreated.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_dateCreatedFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_dateCreatedFocusLost(evt);
            }
        });

        txt_note.setColumns(20);
        txt_note.setRows(5);
        txt_note.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_noteFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_noteFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txt_note);

        btn_add.setBackground(new java.awt.Color(0, 204, 51));
        btn_add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/PolyPro/icons/Add.png"))); // NOI18N
        btn_add.setText("THÊM");
        btn_add.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 51, 0));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/PolyPro/icons/Delete.png"))); // NOI18N
        btn_delete.setText("XÓA");
        btn_delete.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_new.setBackground(new java.awt.Color(0, 204, 204));
        btn_new.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/PolyPro/icons/refresh-icon.png"))); // NOI18N
        btn_new.setText("MỚI");
        btn_new.setMargin(new java.awt.Insets(5, 5, 5, 5));
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_last.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_last.setText(">|");
        btn_last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lastActionPerformed(evt);
            }
        });

        btn_next.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_next.setText(">>");
        btn_next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nextActionPerformed(evt);
            }
        });

        btn_prev.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_prev.setText("<<");
        btn_prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prevActionPerformed(evt);
            }
        });

        btn_first.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_first.setText("|<");
        btn_first.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_firstActionPerformed(evt);
            }
        });

        txt_creator.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_creatorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_creatorFocusLost(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(255, 255, 0));
        btn_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/PolyPro/icons/Edit.png"))); // NOI18N
        btn_edit.setText("SỬA");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        lbl_tenCD.setFont(new java.awt.Font("Segoe UI", 3, 13)); // NOI18N
        lbl_tenCD.setForeground(new java.awt.Color(255, 0, 0));
        lbl_tenCD.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Chuyên đề");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Học phí");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Người tạo");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("Khai giảng *");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Thời lượng (Giờ)");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("Ngày tạo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_creator, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                .addComponent(txt_tuition, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lbl_tenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_openningDay)
                            .addComponent(txt_time)
                            .addComponent(txt_dateCreated, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btn_first)
                        .addGap(18, 18, 18)
                        .addComponent(btn_prev)
                        .addGap(18, 18, 18)
                        .addComponent(btn_next)
                        .addGap(18, 18, 18)
                        .addComponent(btn_last))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_openningDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_tenCD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_time)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_tuition))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_dateCreated)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_creator, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_first)
                        .addComponent(btn_prev)
                        .addComponent(btn_next)
                        .addComponent(btn_last))
                    .addComponent(btn_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabs.addTab("CẬP NHẬT", jPanel1);

        jScrollPane3.setBorder(null);

        tbl_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_list.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_list);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        tabs.addTab("DANH SÁCH", jPanel2);

        cbo_thematic.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbo_thematic.setForeground(new java.awt.Color(0, 0, 204));
        cbo_thematic.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chuyên Đề" }));
        cbo_thematic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_thematicActionPerformed(evt);
            }
        });

        lbl_viewAll.setFont(new java.awt.Font("Tahoma", 3, 15)); // NOI18N
        lbl_viewAll.setForeground(new java.awt.Color(0, 0, 255));
        lbl_viewAll.setText("Xem tất cả");
        lbl_viewAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_viewAll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_viewAllMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_viewAllMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_viewAllMouseExited(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(cbo_thematic, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_viewAll, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbo_thematic, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_viewAll))
                .addGap(18, 18, 18)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_openningDayFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_openningDayFocusGained
        // TODO add your handling code here:
        if(txt_openningDay.getText().equals("dd/MM/yyyy")){
            txt_openningDay.setText("");
            txt_openningDay.requestFocus();
            DesignHelper.deleteTextField(txt_openningDay);
        }
    }//GEN-LAST:event_txt_openningDayFocusGained

    private void txt_openningDayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_openningDayFocusLost
        // TODO add your handling code here:
        if(txt_openningDay.getText().length() == 0){
            txt_openningDay.setText("dd/MM/yyyy");
            DesignHelper.addTextField(txt_openningDay);
        }
    }//GEN-LAST:event_txt_openningDayFocusLost

    private void txt_tuitionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tuitionFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tuitionFocusGained

    private void txt_tuitionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tuitionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tuitionFocusLost

    private void txt_timeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_timeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timeFocusGained

    private void txt_timeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_timeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timeFocusLost

    private void txt_creatorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_creatorFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_creatorFocusGained

    private void txt_creatorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_creatorFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_creatorFocusLost

    private void txt_dateCreatedFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dateCreatedFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateCreatedFocusGained

    private void txt_dateCreatedFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_dateCreatedFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_dateCreatedFocusLost

    private void txt_noteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_noteFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noteFocusGained

    private void txt_noteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_noteFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noteFocusLost

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        if(isValidate()){
            this.insert();
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void cbo_thematicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_thematicActionPerformed
        // TODO add your handling code here:
        this.chooseChuyenDe();
    }//GEN-LAST:event_cbo_thematicActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void lbl_viewAllMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewAllMouseClicked
        // TODO add your handling code here:
        fillAllToTable();
        tabs.setSelectedIndex(1);
    }//GEN-LAST:event_lbl_viewAllMouseClicked

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        if(isValidate()){
            this.update();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void tbl_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tbl_list.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tbl_listMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_firstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_firstActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btn_firstActionPerformed

    private void btn_prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btn_prevActionPerformed

    private void btn_nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btn_nextActionPerformed

    private void btn_lastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btn_lastActionPerformed

    private void lbl_viewAllMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewAllMouseEntered
        // TODO add your handling code here:
        DesignHelper.hoverEnter(lbl_viewAll);
    }//GEN-LAST:event_lbl_viewAllMouseEntered

    private void lbl_viewAllMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_viewAllMouseExited
        // TODO add your handling code here:
        DesignHelper.hoverExit(lbl_viewAll);
    }//GEN-LAST:event_lbl_viewAllMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KhoaHocJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KhoaHocJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_first;
    private javax.swing.JButton btn_last;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_next;
    private javax.swing.JButton btn_prev;
    private javax.swing.JComboBox<Object> cbo_thematic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel lbl_tenCD;
    private javax.swing.JLabel lbl_viewAll;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_list;
    private javax.swing.JTextField txt_creator;
    private javax.swing.JTextField txt_dateCreated;
    private javax.swing.JTextArea txt_note;
    private javax.swing.JTextField txt_openningDay;
    private javax.swing.JTextField txt_time;
    private javax.swing.JTextField txt_tuition;
    // End of variables declaration//GEN-END:variables

    public void init() {
        setLocationRelativeTo(null);
        this.setTitle("HỆ THỐNG QUẢN LÝ ĐÀO TẠO");
        setTitle();
        setEnable();
        this.fillComboBoxChuyenDe();
        this.fillToTable();
        updateStatus();
    }

    public void setTitle() {
        model = new DefaultTableModel();
        model.addColumn("Mã KH");
        model.addColumn("Chuyên đề");
        model.addColumn("Thời lượng");
        model.addColumn("Học phí");
        model.addColumn("Ngày khai giảng");
        model.addColumn("Tạo bởi");
        model.addColumn("Ngày tạo");
        tbl_list.setModel(model);

        DesignHelper.setTable(tbl_list);
    }

    /* Viết mã cho các chức năng */
    KhoaHocDAO dao = new KhoaHocDAO();
    ChuyenDeDAO cddao = new ChuyenDeDAO();
    int row = -1;
    int maKH = 0;

    void fillComboBoxChuyenDe() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cbo_thematic.getModel();
        model.removeAllElements();
        List<ChuyenDe> list = cddao.selectAll();
        for (ChuyenDe cd : list) {
            model.addElement(cd);
        }
    }

    void fillToTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_list.getModel();
        model.setRowCount(0);
        try {
            ChuyenDe chuyenDe = (ChuyenDe) cbo_thematic.getSelectedItem();
            if(chuyenDe != null){
                List<KhoaHoc> list = dao.selectByChuyenDe(chuyenDe.getMaCD());
            for (KhoaHoc kh : list) {
                model.addRow(new Object[]{
                    kh.getMaKH(),
                    kh.getMaCD(),
                    kh.getThoiLuong(),
                    kh.getHocPhi(),
                    DateHelper.toString(kh.getNgayKG(), "dd/MM/yyyy"),
                    kh.getMaNV(),
                    DateHelper.toString(kh.getNgayTao(), "dd/MM/yyyy")});
            }
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void fillAllToTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_list.getModel();
        model.setRowCount(0);
        try {
            List<KhoaHoc> list = dao.selectAll();
            for (KhoaHoc kh : list) {
                model.addRow(new Object[]{
                    kh.getMaKH(),
                    kh.getMaCD(),
                    kh.getThoiLuong(),
                    kh.getHocPhi(),
                    DateHelper.toString(kh.getNgayKG(), "dd/MM/yyyy"),
                    kh.getMaNV(),
                    DateHelper.toString(kh.getNgayTao(), "dd/MM/yyyy")});
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    void clear() {
        ChuyenDe cd = new ChuyenDe();
        KhoaHoc kh = new KhoaHoc();
        maKH = 0;
        txt_openningDay.setText("dd/MM/yyyy");
        DesignHelper.addTextField(txt_openningDay);
        DesignHelper.setBackgroundDefault(txt_openningDay);
        txt_creator.setText(ShareHelper.user.getMaNV());
        txt_dateCreated.setText(DateHelper.toString(kh.getNgayTao(), "dd/MM/yyyy"));
        ChuyenDe chuyenDe = cddao.selectById(kh.getMaCD());
        maKH = kh.getMaKH();
        lbl_tenCD.setText(cd.getTenCD());
        txt_tuition.setText(String.valueOf(kh.getHocPhi()));
        txt_time.setText(String.valueOf(kh.getThoiLuong()));
        txt_note.setText(kh.getGhiChu());
        
        this.row = -1;
        updateStatus();
    }

    KhoaHoc getForm() {
        KhoaHoc kh = new KhoaHoc();
        ChuyenDe cd = (ChuyenDe) cbo_thematic.getSelectedItem();
        kh.setMaCD(cd.getMaCD());
        kh.setNgayKG(DateHelper.toDate(txt_openningDay.getText(), "dd/MM/yyyy"));
        kh.setHocPhi(Double.parseDouble(txt_tuition.getText()));
        kh.setThoiLuong(Integer.parseInt(txt_time.getText()));
        kh.setMaNV(ShareHelper.user.getMaNV());
        kh.setNgayTao(DateHelper.toDate(txt_dateCreated.getText(), "dd/MM/yyyy"));
        kh.setGhiChu(txt_note.getText());
        if (maKH != 0) {
            kh.setMaKH(maKH);
            System.out.println(maKH);
        }
        return kh;
    }

    void setForm(KhoaHoc kh, ChuyenDe cd) {
        txt_openningDay.setText(DateHelper.toString(kh.getNgayKG(), "dd/MM/yyyy"));
        DesignHelper.setBackgroundDefault(txt_openningDay);
        txt_creator.setText(kh.getMaNV());
        txt_dateCreated.setText(DateHelper.toString(kh.getNgayTao(), "dd/MM/yyyy"));
        ChuyenDe chuyenDe = cddao.selectById(kh.getMaCD());
        maKH = kh.getMaKH();
        lbl_tenCD.setText(cd.getTenCD());
        txt_tuition.setText(String.valueOf(kh.getHocPhi()));
        txt_time.setText(String.valueOf(kh.getThoiLuong()));
        txt_note.setText(kh.getGhiChu());
    }

    void edit() {
        String maKH = String.valueOf(tbl_list.getValueAt(this.row, 0));
        KhoaHoc kh = dao.selectById(maKH);
        ChuyenDe cd = (ChuyenDe) cddao.selectById(kh.getMaCD());
        this.setForm(kh, cd);
        this.updateStatus();
        tabs.setSelectedIndex(0);
    }

    void insert() {
        KhoaHoc kh = getForm();
        try {
            dao.insert(kh);
            this.fillToTable();
            this.clear();
            DialogHelper.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Thêm mới thất bại!" + e);
        }
    }

    void update() {
        KhoaHoc kh = getForm();
        try {
            dao.update(kh);
            this.fillToTable();
            DesignHelper.setBackgroundDefault(txt_openningDay);
            DialogHelper.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại!");
        }
    }

    void delete() {
        try {
            if (DialogHelper.confirm(this, "Bạn có muốn xóa khóa học này?")) {
                dao.delete(String.valueOf(maKH));
                this.fillAllToTable();
                this.clear();
                DialogHelper.alert(this, "Xóa thành công!");
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Xóa thất bại!");
        }
    }

    void chooseChuyenDe() {
        ChuyenDe cd = (ChuyenDe) cbo_thematic.getSelectedItem();
        if (cd != null) {
            txt_time.setText(String.valueOf(cd.getThoiLuong()));
            txt_tuition.setText(String.valueOf(cd.getHocPhi()));
            lbl_tenCD.setText(cd.getTenCD());
            txt_note.setText(cd.getTenCD());
            txt_creator.setText(ShareHelper.user.getMaNV());
            txt_dateCreated.setText(DateHelper.toString(DateHelper.now(), "dd/MM/yyyy"));

            this.fillToTable();
            this.row = -1;
            this.updateStatus();
            tabs.setSelectedIndex(1);
        }
    }

    void first() {
        this.row = 0;
        this.edit();
    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void next() {
        if (this.row < tbl_list.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    void last() {
        this.row = tbl_list.getRowCount() - 1;
        this.edit();
    }

    void setEnable(){
        lbl_tenCD.setEnabled(false);
        lbl_tenCD.setForeground(new Color(255,0,0));
        txt_time.setEditable(false);
        txt_tuition.setEditable(false);
        txt_creator.setEditable(false);
        txt_dateCreated.setEditable(false);
    }
    
    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tbl_list.getRowCount() - 1);

        // set trạng thái form
        btn_add.setEnabled(!edit);
        btn_edit.setEnabled(edit);
        btn_delete.setEnabled(edit);

        // trạng thái điều hướng
        btn_first.setEnabled(edit && !first);
        btn_prev.setEnabled(edit && !first);
        btn_next.setEnabled(edit && !last);
        btn_last.setEnabled(edit && !last);
    }
    
    boolean isValidate(){
        String notification = "";
        if(txt_openningDay.getText().equalsIgnoreCase("dd/MM/yyyy")){
            notification += "Vui lòng nhập ngày khai giảng!\n";
            DesignHelper.setBackgroundFalse(txt_openningDay);
        }
        else if(ValidateHelper.checkDate(txt_openningDay) == false){
            notification += "Ngày khai giảng không hợp lệ.\n Vui lòng nhập đúng định dạng (dd/MM/yyyy)\n";
        }
        
        if(notification != ""){
            DialogHelper.alert(this, notification);
            return false;
        }
        else{
            DesignHelper.setBackgroundTrue(txt_openningDay);
            return true;
        }
    }
}
